image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - check
  
check:
  stage: check
  script:
    - 'dotnet build ./PrimeAnalyzer'
    - 'dotnet build ./PrimeAnalyzerTest'
    - 'dotnet test ./PrimeAnalyzerTest'