image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  
check:
  stage: test
  script:
    - dotnet build ./PrimeAnalyzer
    - dotnet build ./PrimeAnalyzerTest
    - dotnet test ./PrimeAnalyzerTest
    - ls -la ./PrimeAnalyzer/bin/Debug/net6.0/
    - ./PrimeAnalyzer/bin/Debug/net6.0/PrimeAnalyzer

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
