image: mcr.microsoft.com/dotnet/sdk:latest

build:
  stage: build
  script:
    - 'dotnet build ./PrimeAnalyzer'
    - 'dotnet build ./PrimeAnalyzerTest'

tests:
  stage: test
  script:
    - 'dotnet test ./PrimeAnalyzerTest'